CREATE DATABASE vet_clinic;

CREATE Table animals(
  id  INTEGER GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(50),
  date_of_birth DATE,
  escape_attempts INTEGER,
  neutered BOOLEAN,
  weight_kg DECIMAL,
  PRIMARY KEY(id)
);

ALTER TABLE animals
ADD species VARCHAR(50);

CREATE TABLE owners(
  id INTEGER GENERATED ALWAYS AS IDENTITY,
  full_name VARCHAR(50) NOT NULL,
  age INTEGER NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE species(
  id INTEGER GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
);